// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxh8OZXYdIJRulGcMIdz3ii0IODXCqw00',
    appId: '1:287104460225:web:f0ac2521b447fa7a60fb40',
    messagingSenderId: '287104460225',
    projectId: 'meditation-app-1f40b',
    authDomain: 'meditation-app-1f40b.firebaseapp.com',
    storageBucket: 'meditation-app-1f40b.firebasestorage.app',
    measurementId: 'G-SQMTL7YPQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBarj0z6s7KX2z-JNGtYUvCxqbkw0bo4UE',
    appId: '1:287104460225:android:d77ec5d942ef0a1f60fb40',
    messagingSenderId: '287104460225',
    projectId: 'meditation-app-1f40b',
    storageBucket: 'meditation-app-1f40b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfHrl0-3cEoFhEm_Gx9G-uoGmy2TP0A-o',
    appId: '1:287104460225:ios:ece2bc2ad8632f6960fb40',
    messagingSenderId: '287104460225',
    projectId: 'meditation-app-1f40b',
    storageBucket: 'meditation-app-1f40b.firebasestorage.app',
    iosBundleId: 'com.example.metidationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfHrl0-3cEoFhEm_Gx9G-uoGmy2TP0A-o',
    appId: '1:287104460225:ios:ece2bc2ad8632f6960fb40',
    messagingSenderId: '287104460225',
    projectId: 'meditation-app-1f40b',
    storageBucket: 'meditation-app-1f40b.firebasestorage.app',
    iosBundleId: 'com.example.metidationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxh8OZXYdIJRulGcMIdz3ii0IODXCqw00',
    appId: '1:287104460225:web:1b07eff9a1a5df0e60fb40',
    messagingSenderId: '287104460225',
    projectId: 'meditation-app-1f40b',
    authDomain: 'meditation-app-1f40b.firebaseapp.com',
    storageBucket: 'meditation-app-1f40b.firebasestorage.app',
    measurementId: 'G-BEE9KL85PH',
  );
}
